### ISSUE TITLE
The plugin fetches 100 image not more

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [ExidCuter/docker-registry-explorer-plugin#16]
I have added docker repo and able to see oinly 100 images. I have updated the config:
![image](https://user-images.githubusercontent.com/4487110/236834624-96dad3fc-ff1f-4ed7-954a-0b8bb103d17d.png)

then restrted IDE then readded the url and still only 100 images in the list :(

**Comment by ExidCuter** [comment]
Hi, the plugin is not using any of the Intelij settings. It's probably an issue with the registry API is using pagination. Will have to check that. No promises on when this will be done, because right now I have very little spare time to work on this project. 

You can always open a MR if you need a fix.
