### ISSUE TITLE
certificates not being utilized

### ISSUE THREAD

**Issue by brunnels** [ExidCuter/docker-registry-explorer-plugin#8]
We have a private signing authority for our certificates and the plugin isn't taking them from the system /etc/ssl/certs or from the certs added into intellij Tools -> Server Certificates.  I get this error:

`Docker Registry Error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by ExidCuter** [comment]
Hi! 

Sorry for the late response. I've been quite busy at my day job. 

I've disabled SSL checks for all registries because it's not actually needed (development tool).

I've also submitted the update to the JetBrains Marketplace and it should be available after their review process is completed. In the meantime you can download latest version from [here](https://github.com/ExidCuter/docker-registry-explorer-plugin/releases/tag/1.0.7-stable).
